/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - Measure how data is distributed across key business dimensions
    - Compare customers, products, and revenue at an aggregated level
===============================================================================
*/

-- Total number of customers by country
SELECT 
    country,
    COUNT(DISTINCT customer_key) AS total_customers
FROM dw_gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Total number of customers by gender
-- new_gen = standardized gender field
SELECT 
    new_gen AS gender,
    COUNT(DISTINCT customer_key) AS total_customers
FROM dw_gold.dim_customers
GROUP BY new_gen
ORDER BY total_customers DESC;


-- Total number of products by category
SELECT 
    category,
    COUNT(DISTINCT product_key) AS total_products
FROM dw_gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- Average product cost by category
SELECT 
    category,
    ROUND(AVG(cost), 2) AS avg_cost
FROM dw_gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- Total revenue generated by each category
SELECT 
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM dw_gold.dim_products p
JOIN dw_gold.fact_sales f
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Top 10 customers by total revenue
SELECT  
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM dw_gold.dim_customers c
JOIN dw_gold.fact_sales f
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC
LIMIT 10;


-- Distribution of sales and quantity by country
SELECT  
    c.country,
    SUM(f.sales_amount) AS total_sales,
    SUM(f.quantity) AS total_quantity
FROM dw_gold.fact_sales f
JOIN dw_gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC;
